// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_aplication.DataAccess.Context;

#nullable disable

namespace Web_aplication.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_aplication.Domain.Entities.ContactDetailEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ContactDetails");

                    b.HasData(
                        new
                        {
                            Id = "address",
                            Href = "https://www.google.com/maps",
                            Icon = "fa-solid fa-location-dot",
                            Label = "Adresa",
                            Note = "Chisinau, Moldova",
                            Value = "Stefan cel Mare si Sfant Boulevard 83, MD-2012"
                        },
                        new
                        {
                            Id = "phone",
                            Href = "tel:+37322555700",
                            Icon = "fa-solid fa-phone",
                            Label = "Telefon",
                            Note = "Luni - Vineri, 09:00 - 18:00",
                            Value = "+373 22 555 700"
                        },
                        new
                        {
                            Id = "email",
                            Href = "mailto:contact@moldovatravel.md",
                            Icon = "fa-solid fa-envelope",
                            Label = "Email",
                            Note = "Raspundem in max. 24h",
                            Value = "contact@moldovatravel.md"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.DestinationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tips")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = "orheiul-vechi",
                            Area = "Orhei",
                            Cat = "Natura",
                            Description = "Complex natural și archaeological pe malul râului Răut cu mănăstiri rupestre și vestigii medievale.",
                            Image = "/images/destinatii/orheiul-vechi.jpg",
                            Lat = 47.364400000000003,
                            Lng = 28.978400000000001,
                            Name = "Orheiul Vechi",
                            Tips = "Vizitați dimineața devreme pentru a evita aglomerația. Purtați pantofi comozi."
                        },
                        new
                        {
                            Id = "milestii-mici",
                            Area = "Ialoveni",
                            Cat = "Vin",
                            Description = "Cel mai mare depozit de vinuri din lume (Guinness). Tunelele subterane au peste 200 km.",
                            Image = "/images/destinatii/milestii-mici.jpg",
                            Lat = 46.933300000000003,
                            Lng = 28.899999999999999,
                            Name = "Mileștii Mici",
                            Tips = "Rezervați vizita în avans. Turul se face cu mașina proprie sau cu vehiculele vinăriei."
                        },
                        new
                        {
                            Id = "saharna",
                            Area = "Rezina",
                            Cat = "Manastiri",
                            Description = "Complex monastic ortodox înconjurat de păduri și cascade pe malul Nistrului.",
                            Image = "/images/destinatii/saharna.jpg",
                            Lat = 47.683300000000003,
                            Lng = 28.966699999999999,
                            Name = "Mănăstirea Saharna",
                            Tips = "Respectați codul vestimentar. Traseul spre cascade necesită condiție fizică bună."
                        },
                        new
                        {
                            Id = "soroca",
                            Area = "Soroca",
                            Cat = "Istorie",
                            Description = "Singura cetate circulară din Moldova, construită la ordinul lui Ștefan cel Mare.",
                            Image = "/images/destinatii/cetatea-soroca.jpg",
                            Lat = 48.156100000000002,
                            Lng = 28.2881,
                            Name = "Cetatea Soroca",
                            Tips = "Vizitați și Lumânarea Recunoștinței de pe dealul din spatele cetății."
                        },
                        new
                        {
                            Id = "chisinau",
                            Area = "Chișinău",
                            Cat = "Orase",
                            Description = "Capitala Republicii Moldova cu parcuri, muzee, restaurante și viață culturală activă.",
                            Image = "/images/destinatii/chisinau.jpg",
                            Lat = 47.0105,
                            Lng = 28.863800000000001,
                            Name = "Chișinău",
                            Tips = "Vizitați Grădina Publică Ștefan cel Mare și Sfânt și Piața Centrală."
                        },
                        new
                        {
                            Id = "codrii",
                            Area = "Strășeni",
                            Cat = "Natura",
                            Description = "Cea mai mare rezervație naturală din Moldova (5.177 ha) cu biodiversitate bogată.",
                            Image = "/images/destinatii/codrii.jpg",
                            Lat = 47.116700000000002,
                            Lng = 28.416699999999999,
                            Name = "Rezervația Codrii",
                            Tips = "Obțineți permisul de acces în avans. Traseele marcate sunt recomandate."
                        },
                        new
                        {
                            Id = "cricova",
                            Area = "Cricova",
                            Cat = "Vin",
                            Description = "Vinărie renumită pentru tunelurile de 120 km săpate în calcar.",
                            Image = "/images/destinatii/cricova.jpg",
                            Lat = 47.133299999999998,
                            Lng = 28.866700000000002,
                            Name = "Cricova",
                            Tips = "Rezervați turul cu cel puțin o săptămână înainte în sezonul turistic."
                        },
                        new
                        {
                            Id = "tipova",
                            Area = "Rezina",
                            Cat = "Manastiri",
                            Description = "Cel mai vechi complex monahal din Moldova, săpat în stânca de pe malul Nistrului.",
                            Image = "/images/destinatii/tipova.jpg",
                            Lat = 47.700000000000003,
                            Lng = 29.0167,
                            Name = "Mănăstirea Tipova",
                            Tips = "Traseul este abrupt. Nu este recomandat pe vreme ploioasă."
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.FaqItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("FaqItems");

                    b.HasData(
                        new
                        {
                            Id = "reserve-tour",
                            Answer = "Poti rezerva direct din pagina Rute sau contactandu-ne.",
                            Category = "Planificare si rezervari",
                            Question = "Cum pot rezerva un tur?"
                        },
                        new
                        {
                            Id = "reserve-early",
                            Answer = "Da, este recomandat, mai ales in weekend sau sezonul turistic.",
                            Category = "Planificare si rezervari",
                            Question = "Trebuie sa rezerv din timp?"
                        },
                        new
                        {
                            Id = "language",
                            Answer = "Limba oficiala este romana, dar se vorbeste si rusa sau engleza.",
                            Category = "Informatii generale",
                            Question = "Ce limba se vorbeste in Moldova?"
                        },
                        new
                        {
                            Id = "safety",
                            Answer = "Da, este o destinatie sigura pentru turisti.",
                            Category = "Informatii generale",
                            Question = "Este sigur sa calatoresc in Moldova?"
                        },
                        new
                        {
                            Id = "best-season",
                            Answer = "Primavara si toamna sunt cele mai potrivite.",
                            Category = "Organizare",
                            Question = "Care este cea mai buna perioada?"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.GalleryBlockEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GalleryBlocks");

                    b.HasData(
                        new
                        {
                            Id = "gallery-seed-1",
                            Subtitle = "Culorile soarelui apune deasupra stâncilor",
                            Theme = "galerie-sunset",
                            Title = "Apus la Orheiul Vechi"
                        },
                        new
                        {
                            Id = "gallery-seed-2",
                            Subtitle = "Tradiție și pasiune în fiecare pahar",
                            Theme = "galerie-vin",
                            Title = "Vinurile Moldovei"
                        },
                        new
                        {
                            Id = "gallery-seed-3",
                            Subtitle = "Peisaje pitorești de pe malul Nistrului",
                            Theme = "galerie-nistru",
                            Title = "Nistrul albastru"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.GuideChecklistItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GuideItems");

                    b.HasData(
                        new
                        {
                            Id = "guide-1-documente",
                            Description = "Pașaport sau buletin valabil. Cetățenii UE nu au nevoie de viză.",
                            Title = "Documente"
                        },
                        new
                        {
                            Id = "guide-2-valuta",
                            Description = "Leul moldovenesc (MDL). Cardurile sunt acceptate în orașe.",
                            Title = "Valută"
                        },
                        new
                        {
                            Id = "guide-3-transport",
                            Description = "Mașina proprie sau închiriată oferă cel mai mult confort.",
                            Title = "Transport"
                        },
                        new
                        {
                            Id = "guide-4-cazare",
                            Description = "Rezervați din timp, mai ales pentru sezonul turistic (mai-septembrie).",
                            Title = "Cazare"
                        },
                        new
                        {
                            Id = "guide-5-haine",
                            Description = "Haine lejere vara, strat termic toamna. Pantofi comozi pentru drumeții.",
                            Title = "Îmbrăcăminte"
                        },
                        new
                        {
                            Id = "guide-6-vinarii",
                            Description = "Rezervați în avans. Cricova și Mileștii Mici sunt obligatorii.",
                            Title = "Vizite la vinării"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.OfficeLocationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OfficeLocation");

                    b.HasData(
                        new
                        {
                            Id = "office",
                            Address = "Stefan cel Mare si Sfant Boulevard 83, MD-2012",
                            City = "Chisinau",
                            Lat = 47.022743599999998,
                            Lng = 28.834643199999999,
                            Name = "Moldova Travel Hub",
                            Schedule = "Luni - Vineri, 09:00 - 18:00"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.RoutePoiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("RoutePois");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Punct de start și informații despre traseu",
                            Lat = 47.116700000000002,
                            Lng = 28.416699999999999,
                            RouteId = "codrii",
                            Title = "Centrul Rezervației"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Loc de odihnă cu fagi seculari",
                            Lat = 47.125,
                            Lng = 28.414999999999999,
                            RouteId = "codrii",
                            Title = "Poiana Fagilor"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Priveliște panoramică asupra rezervației",
                            Lat = 47.130000000000003,
                            Lng = 28.41,
                            RouteId = "codrii",
                            Title = "Belvedere Codrii"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "Punct de plecare din capitală",
                            Lat = 47.0105,
                            Lng = 28.863800000000001,
                            RouteId = "auto-vin",
                            Title = "Chișinău"
                        },
                        new
                        {
                            Id = 5,
                            Desc = "Tuneluri de 120 km în calcar",
                            Lat = 47.133299999999998,
                            Lng = 28.866700000000002,
                            RouteId = "auto-vin",
                            Title = "Cricova"
                        },
                        new
                        {
                            Id = 6,
                            Desc = "Record Guinness — cel mai mare depozit de vinuri",
                            Lat = 46.933300000000003,
                            Lng = 28.899999999999999,
                            RouteId = "auto-vin",
                            Title = "Mileștii Mici"
                        },
                        new
                        {
                            Id = 7,
                            Desc = "Plecare",
                            Lat = 47.0105,
                            Lng = 28.863800000000001,
                            RouteId = "saharna-tipova",
                            Title = "Chișinău"
                        },
                        new
                        {
                            Id = 8,
                            Desc = "Complex monastic cu cascade și izvoare",
                            Lat = 47.683300000000003,
                            Lng = 28.966699999999999,
                            RouteId = "saharna-tipova",
                            Title = "Mănăstirea Saharna"
                        },
                        new
                        {
                            Id = 9,
                            Desc = "Cel mai vechi complex rupestru din Moldova",
                            Lat = 47.700000000000003,
                            Lng = 29.0167,
                            RouteId = "saharna-tipova",
                            Title = "Mănăstirea Tipova"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.SocialLinkEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SocialLinks");

                    b.HasData(
                        new
                        {
                            Id = "instagram",
                            Href = "https://www.instagram.com/explore/tags/moldovatravel/",
                            Icon = "fa-brands fa-instagram",
                            Label = "Instagram"
                        },
                        new
                        {
                            Id = "facebook",
                            Href = "https://www.facebook.com/search/top?q=moldova%20travel",
                            Icon = "fa-brands fa-facebook-f",
                            Label = "Facebook"
                        },
                        new
                        {
                            Id = "tiktok",
                            Href = "https://www.tiktok.com/search?q=moldova%20travel",
                            Icon = "fa-brands fa-tiktok",
                            Label = "TikTok"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.TouristRouteEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BottomPillsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("LineJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TopPillsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = "codrii",
                            BottomPillsJson = "[{\"icon\":\"fa-solid fa-mountain\",\"label\":\"Dificultate medie\"},{\"icon\":\"fa-solid fa-tree\",\"label\":\"Natură\"}]",
                            Category = "Drumetie",
                            Details = "Traseul prin Rezervația Codrii vă duce prin păduri seculare de stejar și fag, cu oportunități de a observa fauna locală.",
                            DurationDays = 1,
                            LineJson = "[[47.1167,28.4167],[47.12,28.42],[47.125,28.415],[47.13,28.41],[47.128,28.405]]",
                            Subtitle = "Drumeție prin cea mai mare rezervație naturală",
                            Title = "Codrii — Inima Pădurilor Moldovei",
                            TopPillsJson = "[{\"icon\":\"fa-solid fa-route\",\"label\":\"15 km\"},{\"icon\":\"fa-solid fa-person-hiking\",\"label\":\"Drumetie\"},{\"icon\":\"fa-solid fa-clock\",\"label\":\"1 zi\"}]"
                        },
                        new
                        {
                            Id = "auto-vin",
                            BottomPillsJson = "[{\"icon\":\"fa-solid fa-wine-glass\",\"label\":\"Degustare\"},{\"icon\":\"fa-solid fa-star\",\"label\":\"Top destinație\"}]",
                            Category = "Vinarii",
                            Details = "Vizitați Cricova (120 km tuneluri) și Mileștii Mici (record Guinness) în aceeași zi.",
                            DurationDays = 1,
                            LineJson = "[[47.0105,28.8638],[47.1333,28.8667],[46.9333,28.9]]",
                            Subtitle = "Cel mai bun vin din Moldova într-o singură zi",
                            Title = "Ruta Vinurilor — Cricova & Mileștii Mici",
                            TopPillsJson = "[{\"icon\":\"fa-solid fa-route\",\"label\":\"60 km\"},{\"icon\":\"fa-solid fa-car\",\"label\":\"Auto\"},{\"icon\":\"fa-solid fa-clock\",\"label\":\"1 zi\"}]"
                        },
                        new
                        {
                            Id = "saharna-tipova",
                            BottomPillsJson = "[{\"icon\":\"fa-solid fa-church\",\"label\":\"Mănăstiri\"},{\"icon\":\"fa-solid fa-water\",\"label\":\"Cascade\"}]",
                            Category = "Natura",
                            Details = "Excursie de două zile cu vizite la mănăstirea Saharna și mănăstirea rupestră Tipova.",
                            DurationDays = 2,
                            LineJson = "[[47.0105,28.8638],[47.6833,28.9667],[47.7,29.0167]]",
                            Subtitle = "Mănăstiri rupestre și cascade pe Nistru",
                            Title = "Saharna & Tipova — Pe Malul Nistrului",
                            TopPillsJson = "[{\"icon\":\"fa-solid fa-route\",\"label\":\"180 km\"},{\"icon\":\"fa-solid fa-car\",\"label\":\"Auto\"},{\"icon\":\"fa-solid fa-clock\",\"label\":\"2 zile\"}]"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "admin123",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "user123",
                            Role = "user",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.RoutePoiEntity", b =>
                {
                    b.HasOne("Web_aplication.Domain.Entities.TouristRouteEntity", "Route")
                        .WithMany("Points")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Web_aplication.Domain.Entities.TouristRouteEntity", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
